project_id = "fywvjgfjnzicfvtzosyu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[[fetch.services]]
url = "http://plate.hbsmservice.com:8080"