// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fywvjgfjnzicfvtzosyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5d3ZqZ2ZqbnppY2Z2dHpvc3l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU4MDY3MzksImV4cCI6MjA1MTM4MjczOX0.YAj96wWap50FlDilsdSL9WX6GrRofeXjcI6gfDGOhok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);